### ISSUE TITLE
Pasting text sometimes missed a character

### ISSUE THREAD

**Issue by smathieu** [rainforestapp/Flashlight-vnc#8]

**Comment by jbarber** [comment]
I'm going to guess this is because the client send the keypresses "too quickly" for the server to keep up...

This is probably related to https://github.com/rainforestapp/Flashlight-vnc/issues/15
 and resolved by https://github.com/rainforestapp/Flashlight-vnc/commit/d7623468d15f95ac6a473453b010961785c203f8
